### ISSUE TITLE
Any chance of docker?

### ISSUE THREAD

**Issue by ochompsky** [dennisrazumovsky/precizer#1]
This seems like a perfect program for a large migration I just did.  I'm trying to get this to run on Unraid, it's Slackware based but has no build tools on it, so im thinking docker is my best chance.  Trying to get it to run but i've never created a container before.

**Comment by eitijupaenoithoowohd** [comment]
To be honest, I can’t imagine how precizer can work outside of a docker container. The resources must be mounted inside the container so that the program can access them. I believe AppImage could help in this case, but despite all my attempts I have not yet been able to create a package based on it.

**Comment by dennisrazumovsky** [comment]
Unraid based on Slackware. And I think I have a solution:
0. Get Slackware iso file
1. Install Slackware on any virtual guest.
2. Build static execution file of precizer
3. Copy that file to Unraid and run.
That's it.
